[package]
name = "vkrender"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "^0.30"
vulkano = "0.28"
vulkano-shaders = "0.28"
vulkano-win = "0.28"
winit = "^0.26"

protocol = {path = "../protocol"}
xpbd = {path = "../xpbd"}
material = {path = "../material"}
