[package]
name = "xpbd"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "^0.30"
rayon = "^1.5"
dyn-clone = "1.0"
fnv = "1.0"
rand = "^0.8"

protocol = {path = "../protocol"}
timer = {path = "../timer"}
