[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "^0.30"

[dependencies.sdl2]
version = "^0.35"
features = ["gfx"]

[dependencies.protocol]
path = "../protocol"

[dependencies.xpbd]
path = "../xpbd"
